### ISSUE TITLE
Getting no data

### ISSUE THREAD

**Issue by janschmidt76** [CSchoch/OR_WE_Energy_Meter#2]
Hi Christoph, I'm trying to get this running on an OR-WE-514 (single phase). The register addresses should be the same on all OR-WE-? But all I get are wrong values. I think it should at least show some values for L1?

Best regards,
Jan

```
Voltage
L1: -1.00 L2: -1.00 L3: -1.00
Freq: -1.00
Current
L1: -1.00 L2: -1.00 L3: -1.00
ActivePower
Total -1.00 L1: -1.00 L2: -1.00 L3: -1.00
Reactive Power
Total: -1.00 L1: -1.00 L2: -1.00 L3: -1.00
Apparent Power
Total: -1.00 L1: -1.00 L2: -1.00 L3: -1.00
Power Factor
Total: -1.00 L1: -1.00 L2: -1.00 L3: -1.00
Counter Active Power
Total: -1.00 L1: -1.00 L2: -1.00 L3: -1.00
Counter Reactive Power
Total: -1.00 L1: -1.00 L2: -1.00 L3: -1.00
Counter Import Active Power
Total: -1.00 L1: -1.00 L2: -1.00 L3: -1.00
Counter Import Reactive Power
Total: -1.00 L1: -1.00 L2: -1.00 L3: -1.00
Counter Export Active Power
Total: 0.00 L1: ovf L2: 0.00 L3: 0.00
Counter Export Reactive Power
Total: -1.00 L1: -1.00 L2: -1.00 L3: -1.00
getSerialNo: 0
getMeterId: 0
getBusBaud: 0
getSoftwareVersion: -1.00
getHardwareVersion: -1.00
getCountRate: 0
getS0Rate: -1.00
getA3: 0
getCycleTime: 0
getCrc: 0
getCombinedCode: 0
```

**Comment by CSchoch** [comment]
Looks like there is no modbus connection, did you check the modbus serial converters leds tx and rx should blink alternating. May be try reversesing them. Also A and B could be wrong. I'am getting a similar result if i unplug my modbus converter.

**Comment by janschmidt76** [comment]
I quickly wrote a "register scanner" yesterday evening and found, that the WE-514 uses completely different registers...

```
Register 300 - Error 2
Register 301 - Error 2
Register 302 - Error 2
Register 303 - Error 2
Register 304 - Result 4999 -> frequency
Register 305 - Result 23528 -> voltage
Register 306 - Error 2
Register 307 - Error 2
```

After that, I found a pdf at github with the correct registers:

[https://github.com/gituser-rk/orno-modbus-mqtt/blob/master/Register%20description%20OR-WE-514%26OR-WE-515.pdf](https://github.com/gituser-rk/orno-modbus-mqtt/blob/master/Register%20description%20OR-WE-514%26OR-WE-515.pdf)

**Comment by CSchoch** [comment]
Are you changing this and may be contribute?

**Comment by janschmidt76** [comment]
I already did some changes for my testing. I'm a little bit unsure about naming conventions, as some functions are "the same" but use different registers and (maybe) data size. Any preferences on this?

**Comment by CSchoch** [comment]
No, may be we can change it to a base class which contains the basic stuff (similar) and 2 derived which handle the special (different) stuff

**Comment by CSchoch** [comment]
I added now classes for all known meters.
